# Generated by Django 5.0.6 on 2024-06-13 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id_artista', models.AutoField(db_column='idArtista', primary_key=True, serialize=False)),
                ('nombre_artista', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_album', models.CharField(max_length=20)),
                ('precio', models.CharField(max_length=10)),
                ('fecha_lanzamiento', models.DateField()),
                ('id_artista', models.ForeignKey(db_column='idArtista', on_delete=django.db.models.deletion.CASCADE, to='productos.artista')),
            ],
        ),
    ]
