# Generated by Django 5.0.6 on 2024-06-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artista',
            old_name='genero',
            new_name='genero_musical',
        ),
    ]
