# Generated by Django 5.0.6 on 2024-06-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_genero_artista_genero_musical'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_img',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='tendencia',
            field=models.BooleanField(default=False),
        ),
    ]
