# Generated by Django 5.0.6 on 2024-06-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_nombre_img_producto_tendencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_album',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_img',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
