# Generated by Django 5.0.6 on 2024-06-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_nombre_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_img',
            field=models.CharField(default='testimg', max_length=50),
        ),
    ]
