# Generated by Django 5.0.6 on 2024-06-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_nombre_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='genero_musical',
        ),
    ]
